services:
  web: 
    build:
      context: app
      target: builder
    stop_signal: SIGINT
    ports:
      - '8000:8000'
  nginx:
    restart: always
    image: nginx:1-alpine
    ports:
      - '80:80'
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
